baseURL = 'http://joshblades.co.uk/'
languageCode = 'en-us'
title = 'Josh Blades'
theme = 'etch'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "ğŸ“ posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "â„¹ï¸ about"
    title = "about"
    url = "/about/"
    weight = 20

[params]
  description = "Your site description"
  copyright = "Copyright Â© 2024 Josh Blades"
  dark = "auto"
  highlight = true

[permalinks]
  posts = "/:title/"